version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: aiblogpost-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: aiblogpost
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./deploy/docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - aiblogpost-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: deploy/docker/backend.Dockerfile
      target: deps
    container_name: aiblogpost-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/aiblogpost?authSource=admin
      JWT_SECRET: your-super-secure-jwt-secret-key-here
      JWT_REFRESH_SECRET: your-super-secure-jwt-refresh-secret-key-here
      OPENAI_API_KEY: your-openai-api-key-here
      GOOGLE_CLIENT_ID: your-google-client-id-here
      GOOGLE_CLIENT_SECRET: your-google-client-secret-here
      GOOGLE_REDIRECT_URI: http://localhost:5000/api/blogspot/callback
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - aiblogpost-network
    command: npm run dev

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aiblogpost-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_APP_NAME: AI Blogpost Generator
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - aiblogpost-network
    command: npm run dev

  # MongoDB Express (Database Management UI)
  mongo-express:
    image: mongo-express:latest
    container_name: aiblogpost-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - aiblogpost-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: aiblogpost-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aiblogpost-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  aiblogpost-network:
    driver: bridge